## YAML Template.
---
spring:
    datasource:
        url: jdbc:h2:mem:appdb
        username : sas
        password: password
        driverClassName: org.h2.Driver
    h2:
        console.enabled: true
    liquibase:
        change-log: db/master.xml